before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
language: python
env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36
install:
  - pip install tox
script:
  - tox
notifications:
  email: false
