before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install: pip install tox-travis
script: tox
notifications:
  email: false
